name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: gulp
      
      - name: Deploy to production
        run: npm run deploy
        if: github.ref == 'refs/heads/main'
      
      - name: Start server
        run: node server.js
        if: github.ref == 'refs/heads/main'
